dubbo.application.name=kk-order-web
dubbo.application.logger=slf4j

dubbo.registry.address=nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
# This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
# For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
dubbo.registry.register-mode=instance

dubbo.protocol.name=tri
dubbo.protocol.port=20931

#避免在启动时检查服务提供者是否存在
dubbo.consumer.check=false

server.port=18031
spring.application.name=kk-order-web

spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.password=

management.endpoints.web.exposure.include=*

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=fb5c6b35-acf9-4685-a60e-016fdb0a1296
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.config.import=optional:nacos:kk-order-web
spring.cloud.nacos.config.refresh-enabled=true

