logging.level.org.apache.dubbo=DEBUG
logging.level.com.alibaba.cloud=DEBUG
logging.level.com.kk.order.center.mapper=DEBUG

spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.namespace=fb5c6b35-acf9-4685-a60e-016fdb0a1296
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
spring.config.import=optional:nacos:kk-order-base-service,optional:nacos:kk-order-center-service
spring.cloud.nacos.config.refresh-enabled=true
